MediWeb/Controllers/PacienteController.cs
using MediWeb.Consultas;
using MediWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MediWeb.Controllers
{
    public class PacienteController : Controller
    {

        PacienteConsulta PacienteConsultas = new PacienteConsulta();
        GeneroConsulta GeneroConsultas = new GeneroConsulta();
        ExpedienteConsulta ExpedienteConsultas = new ExpedienteConsulta();


        public IActionResult Listar( )
        {
            var enfermeraLista = PacienteConsultas.Listar();
          
            return View(enfermeraLista);
        }

        public IActionResult Guardar(Int32 id)
        {

            ViewBag.Expediente = id;
            CargarGenero();

            return View();
        }


        [HttpPost]
        public IActionResult Guardar(PacienteModel doctormodel)
        {
            doctormodel.estado = "REGISTRADO";
            doctormodel.FechaCreacion = DateTime.Now;
          //  doctormodel.ExpedienteId = 0;




            if ((doctormodel.Apellido == "" ) || doctormodel.Nombre == ""
                || (doctormodel.Telefono == "" ) || doctormodel.DNI == ""
                || (doctormodel.Correo == "" ) || doctormodel.Direccion == ""
              //   || (doctormodel.FechaNacimiento == "" ) || doctormodel.FechaCreacion == ""
                  || (doctormodel.Peso == 0) || doctormodel.altura == 0
                //   || (enfermedadmodel.clasificacionId.HasValue && enfermedadmodel.clasificacionId.Value == 0)
                )
            {
                return View();
            }


            var respuesta = PacienteConsultas.Guardar(doctormodel);
            if (respuesta)

                return RedirectToAction("Listar");
            else
                return View();
        }


        public IActionResult Eliminar(Int32 idEnfermedad)
        {

            var enfermedadId = PacienteConsultas.Obtener(idEnfermedad);
            ViewBag.Expediente = enfermedadId.ExpedienteId;
            return View(enfermedadId);

        }


        [HttpPost]
        public IActionResult Eliminar(PacienteModel enfermedadmodel)
        {


            var respuesta = ExpedienteConsultas.Eliminar(enfermedadmodel.ExpedienteId);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();




        }



        [NonAction]
        private void CargarGenero()
        {
            var generos = GeneroConsultas.Listar();


            //    var enfermeraLista = EnfermedadesConsultas.Listar();
            ViewBag.Generos = new SelectList(generos, "id", "Descripcion");

        }



    }
}

MediWeb/Views/Paciente/Eliminar.cshtml
@model PacienteModel




@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}






<div class="card">
    <div class="card-header">
        Eliminar Paciente
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Paciente" method="post">

            <input asp-for="id" type="hidden" class="form-control" id="exampleInputEmail1">
            <input asp-for="ExpedienteId" type="hidden" class="form-control" id="exampleInputEmail1" value="@ViewBag.Expediente">


            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill" /></svg>
                <div>
                    Desea Eliminar este: @Html.DisplayTextFor(m => m.id)?
                </div>
            </div>

            <button type="submit" class="btn btn-danger">
                <i class="bi bi-floppy-fill"></i> Eliminar
            </button>
            <a asp-action="Lista" asp-controller="Paciente" class="btn btn-warning">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

MediWeb/Views/Paciente/Guardar.cshtml
@model PacienteModel



@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}






<div class="card">
    <div class="card-header">
        Crear Paciente
    </div>
    <div class="card-body">

        Expediente

        <form asp-action="Guardar" asp-controller="Paciente" method="post">


                       <div class="mb-3">
                
                <input asp-for="ExpedienteId" type="hidden" class="form-control" id="exampleInputEmail1" value="@ViewBag.Expediente">
                 
            </div>

          
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Nombre" class="text-danger"></span>
              
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Apellido</label>
                <input asp-for="Apellido" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Apellido" class="text-danger"></span>

            </div>


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Telefono</label>
                <input asp-for="Telefono" type="tel" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Telefono" class="text-danger"></span>
           
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">DNI</label>
                <input asp-for="DNI" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="DNI" class="text-danger"></span>

            </div>

            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Correo</label>
                <input asp-for="Correo" type="email" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Correo" class="text-danger"></span>

            </div>


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Direccion</label>
                <textarea asp-for="Direccion" id="Direccion" class="form-control" rows="3" cols="30"> </textarea>
                <span asp-validation-for="Direccion" class="text-danger"></span>
            
            </div>

            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Fecha Nacimiento</label>
                <input asp-for="FechaNacimiento" type="date" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>

            </div>


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Peso (LB)</label>
                <input asp-for="Peso" type="number" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Peso" class="text-danger"></span>

            </div>


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Altura (cm)</label>
                <input asp-for="altura" type="number" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="altura" class="text-danger"></span>

            </div>


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Genero</label>
                <select asp-for="Sexo" class="form-control" asp-items="ViewBag.Generos">
                    <option>--Seleccione Genero</option>
                </select>

            </div>

  @*           <div class="mb-3">
                <a asp-action="Guardar" asp-controller="Expediente" class="btn btn-link"
                   >
                    <i class="bi bi-receipt"></i> Agregar Expediente
                </a>

            </div>
 *@

            <button type="submit" class="btn btn-primary">
                <i class="bi bi-floppy-fill" as></i> Guardar
            </button>
            <a asp-action="Listar" asp-controller="Paciente" class="btn btn-warning">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

MediWeb/Views/Paciente/Listar.cshtml
@model List<PacienteModel>




@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="card">
    <div class="card-header">
        Lista Pacientes
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="expediente" class="btn btn-success"
           >
            <i class="bi bi-plus-circle"></i>
            Crear nuevo
            <input type="hidden" class="form-control" id="exampleInputEmail1" value="@ViewBag.Id">

        </a>
        <br />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>DNI</th>
                    <th>ExpedienteId</th>
                    <th></th>

                </tr>


            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.Nombre</td>
                        <td>@item.Apellido</td>
                        <td>@item.DNI</td>
                         <td>@item.ExpedienteId</td>



                        <td>


                            <a asp-action="Eliminar" asp-controller="Paciente" class="btn btn-danger" asp-route-id="@item.id">
                                <i class="bi bi-x-circle-fill"></i> Eliminar
                            </a>

                      @*       <a asp-action="ListaDoctor" asp-controller="EspecialidadDoctor" class="btn btn-info" asp-route-id="@ViewBag.Id">
                                <i class="bi bi-journal-medical"></i> Especialidad
                            </a>
 *@


                        </td>
                    </tr>

                }
            </tbody>

        </table>


    </div>
</div>