MediWeb/Controllers/ProcedimientosMedicosController.cs
using MediWeb.Consultas;
using MediWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MediWeb.Controllers
{
    public class ProcedimientosMedicosController : Controller
    {

        ProcedimientosMedicosConsulta ProcedimientosMedicosConsultas = new ProcedimientosMedicosConsulta();
    


        public IActionResult ListaDoctor(Int32 id)
        {
            ViewBag.Id = id;
            var enfermeraLista = ProcedimientosMedicosConsultas.Obtener(id);
            return View(enfermeraLista);
        }

        public IActionResult Guardar(Int32 id)
        {
          
            ViewBag.Id = id;
           
            return View();
        }


        [HttpPost]
        public IActionResult Guardar(ProcedimientosMedicosModel doctormodel)
        {


            if ((doctormodel.EspecialidadId == 0) ||  doctormodel.Descripcion == ""
                //   || (enfermedadmodel.clasificacionId.HasValue && enfermedadmodel.clasificacionId.Value == 0)
                )
            {
                return View();
            }


            var respuesta = ProcedimientosMedicosConsultas.Guardar(doctormodel);
            if (respuesta)

                return RedirectToAction("ListaDoctor", new { id = doctormodel.EspecialidadId });
            else
                return View();
        }



        public IActionResult Eliminar(Int32 id)
        {

            var enfermedadId = ProcedimientosMedicosConsultas.ObtenerId(id);
            ViewBag.Idespeciliadad = enfermedadId.EspecialidadId;

            return View(enfermedadId);

        }



        [HttpPost]
        public IActionResult Eliminar(ProcedimientosMedicosModel enfermedadmodel)
        {


            var respuesta = ProcedimientosMedicosConsultas.Eliminar(enfermedadmodel.id);
            if (respuesta)
                return RedirectToAction("ListaDoctor", new { id = enfermedadmodel.EspecialidadId });
            else
                return View();




        }






    }
}

MediWeb/Views/ProcedimientosMedicos/Eliminar.cshtml
@model ProcedimientosMedicosModel



@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="card">
    <div class="card-header">
        Eliminar Procedimiento Medico
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="ProcedimientosMedicos" method="post">

            <input asp-for="id" type="hidden" class="form-control" id="exampleInputEmail1">
            <input asp-for="EspecialidadId" type="hidden" class="form-control" id="exampleInputEmail1">


            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill" /></svg>
                <div>
                    Desea Eliminar este: @Html.DisplayTextFor(m => m.id)?
                </div>
            </div>

            <button type="submit" class="btn btn-danger">
                <i class="bi bi-floppy-fill"></i> Eliminar
            </button>
            <a asp-action="ListaDoctor" asp-controller="ProcedimientosMedicos" class="btn btn-warning" asp-route-id="@ViewBag.Idespeciliadad">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

MediWeb/Views/ProcedimientosMedicos/Guardar.cshtml
@model ProcedimientosMedicosModel


@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}







<div class="card">
    <div class="card-header">
        Crear Procedimientos Medicos
    </div>
    <div class="card-body">

        <form asp-action="Guardar" asp-controller="ProcedimientosMedicos" method="post" asp-route-Id="@ViewBag.Id">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">ID</label>
                <input asp-for="EspecialidadId" type="hidden" class="form-control" id="exampleInputEmail1" value="@ViewBag.Id">

                <span asp-validation-for="EspecialidadId" class="text-danger"></span>

            </div>




            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Descripcion</label>
                <textarea asp-for="Descripcion" id="Descripcion" class="form-control" rows="3" cols="30"> </textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>


            </div>



            <button type="submit" class="btn btn-primary" asp-route-Id="@ViewBag.Id">
                <i class="bi bi-floppy-fill"></i> Guardar
            </button>
            <a asp-action="ListaDoctor" asp-controller="ProcedimientosMedicos" class="btn btn-warning" asp-route-Id="@ViewBag.Id">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

MediWeb/Views/ProcedimientosMedicos/ListaDoctor.cshtml
@model List<ProcedimientosMedicosModel>



@{
    ViewData["Title"] = "ListaDoctor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
    <div class="card-header">
        Lista Procedimientos Especialidad
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="ProcedimientosMedicos" class="btn btn-success"
           asp-route-id="@ViewBag.Id">
            <i class="bi bi-plus-circle"></i>
            Crear nuevo
            <input  type="hidden" class="form-control" id="exampleInputEmail1" value="@ViewBag.Id">

        </a>
        <br />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Descripcion</th>


                    <th></th>

                </tr>


            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.Descripcion</td>


                        <td>


                            <a asp-action="Eliminar" asp-controller="ProcedimientosMedicos" class="btn btn-danger" asp-route-id="@item.id">
                                <i class="bi bi-x-circle-fill"></i> Eliminar
                            </a>

                            <a asp-action="ListaDoctor" asp-controller="EspecialidadDoctor" class="btn btn-info" asp-route-id="@ViewBag.Id">
                                <i class="bi bi-journal-medical"></i> Especialidad
                            </a>

                           

                        </td>
                    </tr>

                }
            </tbody>

        </table>


    </div>
</div>