MediWeb/Controllers/EnfermeraController.cs
using Microsoft.AspNetCore.Mvc;

using MediWeb.Consultas;
using MediWeb.Models;


namespace MediWeb.Controllers
{
    public class EnfermeraController : Controller
    {

        EnfermeraConsulta enfermeraConsultas = new EnfermeraConsulta();

        public IActionResult Listar()
        {
            var enfermeraLista = enfermeraConsultas.Listar();
            return View(enfermeraLista);
        }


        public IActionResult Guardar()
        {

           
            return View();
        }


        [HttpPost]
        public IActionResult Guardar( EnfermeraModel enfermeramodel)
        {

            if(!ModelState.IsValid)
            {
                return View();
            }


            var respuesta = enfermeraConsultas.Guardar(enfermeramodel);
            if(respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }


        public IActionResult Editar( Int32 idEnfermera)
        {

            var enfermeraId = enfermeraConsultas.Obtener(idEnfermera);
            return View(enfermeraId);
  
        }


        [HttpPost]
        public IActionResult Editar(EnfermeraModel enfermeramodel )
        {
            if (!ModelState.IsValid)
            {
                return View();
            }


            var respuesta = enfermeraConsultas.Editar(enfermeramodel);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();

        }




        public IActionResult Eliminar(Int32 idEnfermera)
        {

            var enfermeraId = enfermeraConsultas.Obtener(idEnfermera);
            return View(enfermeraId);

        }


        [HttpPost]
        public IActionResult Eliminar(EnfermeraModel enfermeramodel)
        {
          

            var respuesta = enfermeraConsultas.Eliminar(enfermeramodel.id);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();




        }



    }
}

MediWeb/Views/Enfermera/Editar.cshtml
@model EnfermeraModel




@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="card">
    <div class="card-header">
        Editar Enfermera
    </div>
    <div class="card-body">

        <form asp-action="Editar" asp-controller="Enfermera" method="post">

            <input asp-for="id" type="hidden" class="form-control" id="exampleInputEmail1">

            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Nombre" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Telefono</label>
                <input asp-for="Telefono" type="tel" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Telefono" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">DNI</label>
                <input asp-for="DNI" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="DNI" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Direccion</label>
                <textarea asp-for="Direccion" id="Direccion" class="form-control" rows="3" cols="30"> </textarea>
                <span asp-validation-for="Direccion" class="text-danger"></span>

            </div>


            <button type="submit" class="btn btn-primary"> 
                <i class="bi bi-floppy-fill"></i> Editar
            </button>
            <a asp-action="Listar" asp-controller="Enfermera" class="btn btn-warning">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

MediWeb/Views/Enfermera/Eliminar.cshtml
@model EnfermeraModel





@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="card">
    <div class="card-header">
        Eliminar Enfermera
    </div>
    <div class="card-body">

        <form asp-action="Eliminar" asp-controller="Enfermera" method="post">

            <input asp-for="id" type="hidden" class="form-control" id="exampleInputEmail1">


            <div class="alert alert-danger d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill" /></svg>
                <div>
                   Desea Eliminar este: @Html.DisplayTextFor(m => m.Nombre)?
                </div>
            </div>

            <button type="submit" class="btn btn-danger">
                <i class="bi bi-floppy-fill"></i> Eliminar</button>
            <a asp-action="Listar" asp-controller="Enfermera" class="btn btn-warning">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

MediWeb/Views/Enfermera/Guardar.cshtml
@model EnfermeraModel



@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
    <div class="card-header">
        Crear Enfermera
    </div>
    <div class="card-body">

        <form asp-action="Guardar" asp-controller="Enfermera" method="post">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Nombre" class="text-danger"></span>
              
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Telefono</label>
                <input asp-for="Telefono" type="tel" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Telefono" class="text-danger"></span>
           
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">DNI</label>
                <input asp-for="DNI" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="DNI" class="text-danger"></span>

            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Direccion</label>
                <textarea asp-for="Direccion" id="Direccion" class="form-control" rows="3" cols="30"> </textarea>
                <span asp-validation-for="Direccion" class="text-danger"></span>
            
            </div>

        
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-floppy-fill"></i> Guardar
            </button>
            <a asp-action="Listar" asp-controller="Enfermera" class="btn btn-warning">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

MediWeb/Views/Enfermera/Listar.cshtml
@model List<EnfermeraModel>



@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="card">
    <div class="card-header">
        Lista enfermera
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Enfermera" class="btn btn-success">
            <i class="bi bi-plus-circle"></i>
            Crear nuevo</a>
        <br />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>DNI</th>
                    <th>Direccion</th>
                    <th></th>

                </tr>
              

            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.DNI</td>
                        <td>@item.Direccion</td>
                        <td>
                            <a asp-action="Editar" asp-controller="Enfermera" class="btn btn-primary" asp-route-idEnfermera="@item.id">
                                <i class="bi bi-pencil-square"></i> Editar
                            </a>

                            <a asp-action="Eliminar" asp-controller="Enfermera" class="btn btn-danger" asp-route-idEnfermera="@item.id">
                                <i class="bi bi-x-circle-fill"></i> Eliminar
                            </a>

                        </td>
                    </tr>
                    
                }
            </tbody>

        </table>
 

    </div>
</div>