MediWeb/Controllers/MedicamentoController.cs
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using MediWeb.Consultas;
using MediWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MediWeb.Controllers
{
    public class MedicamentoController : Controller
    {
        private readonly Cloudinary _cloudinary;
        CategoriaConsulta CategoriaConsulta = new CategoriaConsulta();
        MedicamentoConsulta MedicamentoConsultas = new MedicamentoConsulta();


        public MedicamentoController(Cloudinary cloudinary)
        {
            _cloudinary = cloudinary;
        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Lista()
        {
           
            var enfermeraLista = MedicamentoConsultas.Listar();
            return View(enfermeraLista);


        }


        public IActionResult Guardar()
        {
            CargarCategorias();
            return View();
        }




        [HttpPost]
        [Route("upload")]
        public async  Task<IActionResult> Upload(IFormFile file, MedicamentoModel model)
        {


            

            if (file == null || file.Length ==0 ) {
                return BadRequest("No se cargo archivo");

            }

            var uploadParmas = new ImageUploadParams()
                {

                File = new FileDescription(file.FileName, file.OpenReadStream()),
                AssetFolder = "MediWeb"

                };

            var uploadResult = await _cloudinary.UploadAsync(uploadParmas);

            TempData["imgUrl"]= uploadResult.SecureUri.ToString();


            model.imagen = uploadResult.SecureUri.ToString();
            model.Cantidad = 0;
            var respuesta = MedicamentoConsultas.Guardar(model);

            return RedirectToAction("Lista");

        }


        [NonAction]
        private void CargarCategorias()
        {
            var generos = CategoriaConsulta.Listar();


            //    var enfermeraLista = EnfermedadesConsultas.Listar();
            ViewBag.Categorias = new SelectList(generos, "Id", "Descripcion");

        }

    }
}

MediWeb/Views/Medicamento/Guardar.cshtml
@model MedicamentoModel




@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
    <div class="card-header">
        Crear Medicamento
    </div>
    <div class="card-body">

        <form asp-action="Upload" asp-controller="Medicamento" method="post" enctype="multipart/form-data">


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Nombre</label>
                <input asp-for="nombre" type="text" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="nombre" class="text-danger"></span>

            </div>

            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Descripcion</label>
                <textarea asp-for="Descripcion" id="Direccion" class="form-control" rows="3" cols="30"> </textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>

            </div>


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Precio</label>
                <input asp-for="Precio" type="number" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Precio" class="text-danger"></span>

            </div>

         @*     <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Cantidad</label>
                <input asp-for="Cantidad" type="number" class="form-control" id="exampleInputEmail1">
                <span asp-validation-for="Cantidad" class="text-danger"></span>

            </div> *@


            <div class="mb-3">
                <label for="file" class="form-label">Subir foto</label>
                <input class="form-control" type="file" name="file" >
            </div>
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-floppy-fill"></i> Subir
            </button>


            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Categoria</label>
                <select asp-for="CategoriaID" class="form-control" asp-items="ViewBag.Categorias">
                    <option>--Seleccione Categoria</option>
                </select>

            </div>



            <button type="submit" class="btn btn-primary">
                <i class="bi bi-floppy-fill"></i> Guardar
            </button>
            <a asp-action="Lista" asp-controller="Usuario" class="btn btn-warning">
                <i class="bi bi-arrow-left-circle-fill"></i> Volver a la lista
            </a>
        </form>

    </div>
</div>

@* <img src="@TempData["imgUrl"]" class="img-thumbnail"  />
<label>@TempData["imgUrl"]</label> *@

MediWeb/Views/Medicamento/Lista.cshtml
@model List<MedicamentoModel>





@{
    ViewData["Title"] = "Lista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="container">
    <div class="card-header">
        Lista Clasificacion Examen Medico

        <a asp-action="Guardar" asp-controller="Enfermera" class="btn btn-success">
            <i class="bi bi-plus-circle"></i>
            Crear nuevo
        </a>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">

                        <p class="card-text">@item.nombre  @item.Precio</p>
                       
                        <img src="@item.imagen" class="img-thumbnail" />

                        <a asp-action="Lista" asp-controller="ExamenMedico" class="btn btn-primary" asp-route-id="@item.Id">
                            <i class="bi bi-eye"></i> Analisis
                        </a>
                        <a asp-action="Eliminar" asp-controller="Enfermera" class="btn btn-danger" asp-route-idEnfermera="@item.Id">
                            <i class="bi bi-x-circle-fill"></i> Eliminar
                        </a>
                    </div>
                </div>
            </div>

        }
    </div>
</div>